AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  NewCops: enable

require:
  - rubocop-rake

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 40

Style/WordArray:
  Enabled: false

Metrics/ClassLength:
  Max: 110

Metrics/CyclomaticComplexity:
  Max: 10

Style/Lambda:
  EnforcedStyle: literal

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
